const appname = "E-Mart Seller App",
      login = "Login",
      welcome = "Hi, Welcome to",
      email = "Email",
      password = "Password",
      forgotPassword = "Forgot Password?",
      anyProblem = "In case of any difficulty, contact administration",
      credit = "@VivekDevs",
      emailHint  = "eg: vendor@gmail.com",
      passHint = "* * * * * *",
      dashboard = "Dashboard",
      orders = "Orders",
      products = "Products",
      settings = "Settings";

